### ISSUE TITLE
Piece Movement

### ISSUE THREAD

**Issue by rj-pe** [rj-pe/CIS434_Spring2019_G5#10]
- [x] feature/pawn_mvmnt
- [x] feature/knight_mvmnt
- [x] feature/king_mvmnt
- [x] feature/queen_mvmnt
- [x] feature/bishop_mvmnt
- [x] feature/rook_mvmnt

**Comment by rj-pe** [comment]
@Alice434  @gskairyu 
69a03a293cf0439222143fc624eb3dcfbe121bf5
As we discussed in class today, in order to help us get on the same wavelength I've completed an initial version of the king movement feature. 

- I did this by overriding the `getPotentialMoves()` method in the `King.java` class. 

- I've also added some logic (with comments explaining my thoughts) to the main method of `CMDChess.java`. 
- Also check out the helper methods-- `isValidMove()`&  `checkForFriend()` -- which I've added to `BoardPiece.java`.

Please comment below for which pieces you will be writing `getPotentialMoves()` methods. There are six pieces, so each of us should aim for completing two of them.

**Comment by Alice354** [comment]
I had started on Pawn movement and the Queen. I can do the getPotentialMoves() for those 2 pieces

**Comment by rj-pe** [comment]
I will do the Rook class.

**Comment by gskairyu** [comment]
I'll take the bishop and the knight then.
